config/routes.rb
Rails.application.routes.draw do

  root 'user#index', as: 'home' 
  get 'user/new'
  get 'user/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/user' => 'user#new', as: 'new'
  post '/user' => 'user#create'
  patch 'user/create'
  post 'user/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create username: params[:user][:username], email: params[:user][:email], bio: params[:user][:bio]
  	puts params
  	redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ILoveForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

  </head>

  <body>
    <div class="container-fluid">
      <ul class ="navbar navbar-expand-lg navbar-light >
        <li class="navbar">
          <a href="<%= home_path %>" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">Home</a>
        </li>
        <li class="navbar">
          <a href="<%= new_path %>" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Docs');">New User</a>
        </li>
      </ul>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1 class="titre">Bienvenu! Veux-tu être mon nouvel utilisateur?</h1>

<h2>Les utilisateurs déjà inscrits :</h2>

<% @users.each do |user| %>
  <p> @<%= user.username %></p>
<% end %>

app/views/user/new.html.erb
<h1 class="titre">New User</h1>

<p>Inscrivez vous en tant que nouvel utilisateur</p>


<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <p><%= f.text_field :username, placeholder:"username" %></p>
  <p><%= f.text_field :email, placeholder:"email" %></p>
  <p><%= f.text_area :bio, placeholder:"bio", size: "60x12" %></p>
  <p class="btn btn-dark"><%= f.submit "Subscribe new user" %></p>
<% end %>